/**
 * Generates a SQL dump file containing all rows from selected tables in the
 * dev database, formatted as `INSERT ... ON CONFLICT (id) DO UPDATE` so the
 * file is safe to run multiple times against the production database.
 *
 * Output: ./dev-data-for-prod.sql
 *
 * Usage:
 *   pnpm --filter @workspace/scripts exec tsx src/dumpDevDataForProd.ts
 *
 * Then paste the contents of dev-data-for-prod.sql into a SQL tool connected
 * to the production database. Existing prod rows with the same id will be
 * updated; missing rows will be inserted. No data is deleted.
 */
export {};

import { writeFileSync } from "node:fs";
import pg from "pg";

// Full catalog table set in FK-dependency order (parents before children).
// Transactional / user / inventory tables are intentionally excluded — prod
// keeps no real data there (test-only), and they are wiped by TRUNCATE CASCADE.
const TABLES_IN_ORDER = [
  "manufacturers",
  "materials",
  "categories",
  "fabrics",
  "finish_collections",
  "finishes",
  "products",
  "product_materials",
  "product_umbrella_sizes",
  "product_variants",
  "product_images",
  "product_attributes",
  "product_fabric_pools",
  "product_fabric_options",
  "product_finish_pools",
  "product_finish_options",
  "product_finial_options",
  // Umbrella cover/stem catalog config + cross-product recommendations.
  // cover/stem options reference products (base + cover/stem); cover finish
  // prices reference products + finishes; recommendations have no FK (sku-keyed).
  "product_cover_options",
  "product_cover_finish_prices",
  "product_stem_options",
  "product_recommendations",
  "variant_grade_prices",
  "product_sets",
  "product_set_items",
  // Catalog add-on definitions (Marella wall add-ons). Children of products.
  // product_addon_options must precede product_addon_grade_prices (FK). The
  // transactional snapshot tables (cart_item_addons, order_item_addons) are
  // intentionally excluded — they're wiped by TRUNCATE CASCADE like cart/orders.
  "product_addon_options",
  "product_addon_grade_prices",
  // Shipping config (admin Shipping page is the source of truth for ONLINE
  // orders). shipping_rules → shipping_rule_products (FK); shipping_weight_tiers
  // is standalone. These are config, mirrored dev→prod like the catalog.
  "shipping_rules",
  "shipping_rule_products",
  "shipping_weight_tiers",
];

// Tables whose ids have drifted between dev and prod (rows re-seeded/recreated
// independently on each side under different ids for the same natural key).
// ON CONFLICT (id) can't reconcile that — it just collides on the table's
// other unique constraints. These tables have no incoming FKs (verified via
// schema grep), so a full TRUNCATE + reinsert of dev's exact rows is safe and
// avoids id-remapping entirely. Must stay after their FK parents in
// TABLES_IN_ORDER (e.g. product_images after products).
const FULL_REPLACE_TABLES = new Set([
  "product_images",
  "product_fabric_pools",
  "product_finish_pools",
  // Added 2026-07-15: same id-drift class as the three above. No incoming FKs,
  // dev is source of truth. variant_grade_prices had confirmed id drift; the
  // rest are added to prevent the same silent sync failure recurring.
  "variant_grade_prices",
  "finish_collections",
  "product_cover_options",
  "product_cover_finish_prices",
  "product_stem_options",
  "product_addon_grade_prices",
]);

// Tables with the same id-drift problem, but their id IS load-bearing: it's
// the target of a live FK (cart_items/order_items composite FK against
// (product_id, fabric_id|finish_id)), so TRUNCATE would cascade-fail (or
// cascade-delete transactional rows). Instead: upsert keyed on the natural
// unique constraint, omit "id" from the insert entirely (let prod assign its
// own), and never touch the id of an existing matched row — this updates
// dev's content in place while leaving cart/order FK targets untouched.
const NATURAL_KEY_TABLES: Record<string, string[]> = {
  product_materials: ["product_id", "material_id"],
  product_umbrella_sizes: ["product_id", "size_label"],
  product_fabric_options: ["product_id", "fabric_id"],
  product_finish_options: ["product_id", "finish_id"],
};

const client = new pg.Client({ connectionString: process.env.DATABASE_URL });
await client.connect();

function quote(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  if (v instanceof Date) return `'${v.toISOString()}'::timestamptz`;
  if (typeof v === "object") {
    // jsonb
    return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

const out: string[] = [
  "-- Auto-generated by scripts/src/dumpDevDataForProd.ts",
  "-- Safe to re-run: uses INSERT ... ON CONFLICT (id) DO UPDATE.",
  "-- No rows are deleted from prod.",
  "BEGIN;",
  "",
];

for (const table of TABLES_IN_ORDER) {
  const colRes = await client.query<{ column_name: string }>(
    `SELECT column_name FROM information_schema.columns
     WHERE table_schema='public' AND table_name=$1
     ORDER BY ordinal_position`,
    [table],
  );
  const cols = colRes.rows.map((r) => r.column_name);
  if (cols.length === 0) {
    out.push(`-- skip ${table}: not found`);
    continue;
  }

  const naturalKey = NATURAL_KEY_TABLES[table];
  // For natural-key tables, drop "id" entirely — prod assigns its own, and an
  // existing matched row's id (the live FK target) must never be overwritten.
  const insertCols = naturalKey ? cols.filter((c) => c !== "id") : cols;

  const orderBy = naturalKey
    ? naturalKey.map((c) => `"${c}"`).join(", ")
    : `"id"`;
  const rowsRes = await client.query(
    `SELECT ${cols.map((c) => `"${c}"`).join(", ")} FROM "${table}" ORDER BY ${orderBy}`,
  );

  out.push(`-- ${table}: ${rowsRes.rows.length} rows`);
  const fullReplace = FULL_REPLACE_TABLES.has(table);
  if (fullReplace) {
    out.push(`TRUNCATE TABLE "${table}" RESTART IDENTITY;`);
  }
  if (rowsRes.rows.length === 0) {
    out.push("");
    continue;
  }

  const colList = insertCols.map((c) => `"${c}"`).join(", ");
  const updateCols = insertCols.filter(
    (c) => c !== "id" && !(naturalKey ?? []).includes(c),
  );
  const updateList = updateCols
    .map((c) => `"${c}" = EXCLUDED."${c}"`)
    .join(", ");
  const conflictClause = naturalKey
    ? updateCols.length > 0
      ? `ON CONFLICT (${naturalKey.map((c) => `"${c}"`).join(", ")}) DO UPDATE SET ${updateList}`
      : `ON CONFLICT (${naturalKey.map((c) => `"${c}"`).join(", ")}) DO NOTHING`
    : `ON CONFLICT (id) DO UPDATE SET ${updateList}`;

  // Emit batched multi-row INSERTs (≈1000 rows/statement) so applying the dump
  // to a remote prod DB needs ~80 round-trips instead of one per row (~60k).
  const BATCH = 1000;
  for (let i = 0; i < rowsRes.rows.length; i += BATCH) {
    const chunk = rowsRes.rows.slice(i, i + BATCH);
    const tuples = chunk
      .map((row) => `(${insertCols.map((c) => quote(row[c])).join(", ")})`)
      .join(",\n");
    if (fullReplace) {
      // Table was just truncated — plain insert, no conflict possible.
      out.push(`INSERT INTO "${table}" (${colList}) VALUES\n${tuples};`);
      continue;
    }
    out.push(
      `INSERT INTO "${table}" (${colList}) VALUES\n${tuples}\n` +
        `${conflictClause};`,
    );
  }

  // Reset the sequence so future inserts don't collide (skip natural-key tables)
  if (!naturalKey) {
    out.push(
      `SELECT setval(pg_get_serial_sequence('"${table}"', 'id'), ` +
        `GREATEST((SELECT COALESCE(MAX(id), 1) FROM "${table}"), 1));`,
    );
  }
  out.push("");
}

out.push("COMMIT;");
out.push("");

writeFileSync("./dev-data-for-prod.sql", out.join("\n"), "utf8");
await client.end();

console.log(`✓ Wrote ./dev-data-for-prod.sql (${out.length} lines)`);
