/**
 * Generates a SQL dump file containing all rows from selected tables in the
 * dev database, formatted as `INSERT ... ON CONFLICT (id) DO UPDATE` so the
 * file is safe to run multiple times against the production database.
 *
 * Output: ./dev-data-for-prod.sql
 *
 * Usage:
 *   pnpm --filter @workspace/scripts exec tsx src/dumpDevDataForProd.ts
 *
 * Then paste the contents of dev-data-for-prod.sql into a SQL tool connected
 * to the production database. Existing prod rows with the same id will be
 * updated; missing rows will be inserted. No data is deleted.
 */
export {};

import { writeFileSync } from "node:fs";
import pg from "pg";

// Full catalog table set in FK-dependency order (parents before children).
// Transactional / user / inventory tables are intentionally excluded — prod
// keeps no real data there (test-only), and they are wiped by TRUNCATE CASCADE.
const TABLES_IN_ORDER = [
  "manufacturers",
  "materials",
  "categories",
  "fabrics",
  "finish_collections",
  "finishes",
  "products",
  "product_materials",
  "product_variants",
  "product_images",
  "product_attributes",
  "product_fabric_pools",
  "product_fabric_options",
  "product_finish_pools",
  "product_finish_options",
  "product_finial_options",
  "variant_grade_prices",
  "product_sets",
  "product_set_items",
  // Catalog add-on definitions (Marella wall add-ons). Children of products.
  // product_addon_options must precede product_addon_grade_prices (FK). The
  // transactional snapshot tables (cart_item_addons, order_item_addons) are
  // intentionally excluded — they're wiped by TRUNCATE CASCADE like cart/orders.
  "product_addon_options",
  "product_addon_grade_prices",
];

const client = new pg.Client({ connectionString: process.env.DATABASE_URL });
await client.connect();

function quote(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  if (v instanceof Date) return `'${v.toISOString()}'::timestamptz`;
  if (typeof v === "object") {
    // jsonb
    return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

const out: string[] = [
  "-- Auto-generated by scripts/src/dumpDevDataForProd.ts",
  "-- Safe to re-run: uses INSERT ... ON CONFLICT (id) DO UPDATE.",
  "-- No rows are deleted from prod.",
  "BEGIN;",
  "",
];

for (const table of TABLES_IN_ORDER) {
  const colRes = await client.query<{ column_name: string }>(
    `SELECT column_name FROM information_schema.columns
     WHERE table_schema='public' AND table_name=$1
     ORDER BY ordinal_position`,
    [table],
  );
  const cols = colRes.rows.map((r) => r.column_name);
  if (cols.length === 0) {
    out.push(`-- skip ${table}: not found`);
    continue;
  }

  const rowsRes = await client.query(
    `SELECT ${cols.map((c) => `"${c}"`).join(", ")} FROM "${table}" ORDER BY id`,
  );

  out.push(`-- ${table}: ${rowsRes.rows.length} rows`);
  if (rowsRes.rows.length === 0) {
    out.push("");
    continue;
  }

  const colList = cols.map((c) => `"${c}"`).join(", ");
  const updateList = cols
    .filter((c) => c !== "id")
    .map((c) => `"${c}" = EXCLUDED."${c}"`)
    .join(", ");

  // Emit batched multi-row INSERTs (≈1000 rows/statement) so applying the dump
  // to a remote prod DB needs ~80 round-trips instead of one per row (~60k).
  const BATCH = 1000;
  for (let i = 0; i < rowsRes.rows.length; i += BATCH) {
    const chunk = rowsRes.rows.slice(i, i + BATCH);
    const tuples = chunk
      .map((row) => `(${cols.map((c) => quote(row[c])).join(", ")})`)
      .join(",\n");
    out.push(
      `INSERT INTO "${table}" (${colList}) VALUES\n${tuples}\n` +
        `ON CONFLICT (id) DO UPDATE SET ${updateList};`,
    );
  }

  // Reset the sequence so future inserts don't collide
  out.push(
    `SELECT setval(pg_get_serial_sequence('"${table}"', 'id'), ` +
      `GREATEST((SELECT COALESCE(MAX(id), 1) FROM "${table}"), 1));`,
  );
  out.push("");
}

out.push("COMMIT;");
out.push("");

writeFileSync("./dev-data-for-prod.sql", out.join("\n"), "utf8");
await client.end();

console.log(`✓ Wrote ./dev-data-for-prod.sql (${out.length} lines)`);
