import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import { OASIS_LOGO_DATA_URL } from "./oasisLogoData";

/**
 * Customer order receipt PDF.
 *
 * Modeled on the printed "Special Order" form Oasis uses in-store: logo
 * top-left, order number top-right, customer info block, items grid,
 * totals + special instructions, signature line at the bottom. Augmented
 * with vendor (manufacturer) per line item and a payments history block
 * — both required so partial-payment receipts can be reprinted.
 *
 * Two copies are generated by the same renderer; the only difference is
 * the footer label ("CUSTOMER COPY" vs "STORE COPY"). Either copy can be
 * (re)printed any number of times from the staff order detail page.
 */

const OASIS_NAME = "Oasis Garden & Patio";
const OASIS_ADDR1 = "21182 Centre Pointe Pkwy #100";
const OASIS_ADDR2 = "Santa Clarita, CA 91350";
const OASIS_PHONE = "(661) 255-9909";

const BORDER = "#1a1a1a";
const SOFT_BORDER = "#888";
const LIGHT_BG = "#f7f7f5";
const LABEL = "#555";

const s = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 9,
    padding: 28,
    backgroundColor: "#fff",
    color: "#1a1a1a",
  },
  row: { flexDirection: "row" },

  /* ── Top header ───────────────────────────────────────────────── */
  headerRow: { flexDirection: "row", alignItems: "flex-start" },
  brandCol: { width: "55%", paddingRight: 12 },
  brandLogo: { width: 180, height: 64, objectFit: "contain" },
  brandAddr: {
    fontSize: 8,
    textAlign: "center",
    width: 180,
    marginTop: 2,
    lineHeight: 1.3,
  },
  titleCol: { width: "45%", alignItems: "flex-end" },
  formTitle: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
  },
  formNumber: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    border: `1px solid ${BORDER}`,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginTop: 6,
    minWidth: 160,
    textAlign: "center",
  },

  /* ── Customer info block ──────────────────────────────────────── */
  infoTable: {
    border: `1px solid ${BORDER}`,
    marginTop: 12,
  },
  infoRow: {
    flexDirection: "row",
    borderBottom: `1px solid ${BORDER}`,
  },
  infoRowLast: { flexDirection: "row" },
  infoCell: {
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRight: `1px solid ${BORDER}`,
    flexDirection: "row",
    alignItems: "baseline",
  },
  infoCellLast: {
    paddingVertical: 4,
    paddingHorizontal: 6,
    flexDirection: "row",
    alignItems: "baseline",
  },
  infoLabel: {
    fontSize: 7,
    color: LABEL,
    textTransform: "uppercase",
    fontFamily: "Helvetica-Bold",
    marginRight: 6,
  },
  infoValue: { fontSize: 9 },

  /* ── Items table ──────────────────────────────────────────────── */
  itemsTable: {
    border: `1px solid ${BORDER}`,
    marginTop: 12,
  },
  thRow: {
    flexDirection: "row",
    backgroundColor: "#1a1a1a",
    paddingVertical: 4,
  },
  th: {
    color: "#fff",
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    paddingHorizontal: 4,
  },
  tdRow: {
    flexDirection: "row",
    borderBottom: `1px solid ${SOFT_BORDER}`,
    minHeight: 22,
    alignItems: "flex-start",
    paddingVertical: 3,
  },
  td: { fontSize: 8.5, paddingHorizontal: 4 },

  colDept: { width: "10%" },
  colQty: { width: "8%", textAlign: "center" },
  colDesc: { width: "55%" },
  colPrice: { width: "13.5%", textAlign: "right" },
  colAmt: { width: "13.5%", textAlign: "right" },

  itemSub: { fontSize: 7, color: LABEL, marginTop: 1 },

  /* ── Bottom section ───────────────────────────────────────────── */
  bottomRow: { flexDirection: "row", marginTop: 10 },
  notesBox: {
    width: "55%",
    border: `1px solid ${BORDER}`,
    padding: 6,
    marginRight: 8,
  },
  notesLabel: {
    fontSize: 7,
    color: LABEL,
    textTransform: "uppercase",
    fontFamily: "Helvetica-Bold",
    marginBottom: 3,
  },
  notesText: { fontSize: 8.5, lineHeight: 1.35 },

  totalsBox: { width: "45%", border: `1px solid ${BORDER}` },
  totalRow: {
    flexDirection: "row",
    borderBottom: `1px solid ${BORDER}`,
  },
  totalRowLast: { flexDirection: "row" },
  totalLabelCell: {
    width: "55%",
    paddingVertical: 4,
    paddingHorizontal: 6,
    fontFamily: "Helvetica-Bold",
    fontSize: 9,
    textTransform: "uppercase",
    borderRight: `1px solid ${BORDER}`,
    backgroundColor: LIGHT_BG,
  },
  totalValueCell: {
    width: "45%",
    paddingVertical: 4,
    paddingHorizontal: 6,
    fontSize: 9,
    textAlign: "right",
  },
  totalEmphasis: { fontFamily: "Helvetica-Bold" },

  /* ── Payments ─────────────────────────────────────────────────── */
  payTable: {
    border: `1px solid ${BORDER}`,
    marginTop: 12,
  },
  payHeader: {
    backgroundColor: LIGHT_BG,
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderBottom: `1px solid ${BORDER}`,
    fontFamily: "Helvetica-Bold",
    fontSize: 9,
    textTransform: "uppercase",
  },
  payThRow: {
    flexDirection: "row",
    backgroundColor: "#1a1a1a",
    paddingVertical: 3,
  },
  payTdRow: {
    flexDirection: "row",
    borderBottom: `1px solid ${SOFT_BORDER}`,
    paddingVertical: 3,
  },
  payCol: { fontSize: 8, paddingHorizontal: 4 },
  payColDate: { width: "18%" },
  payColMethod: { width: "20%" },
  payColRef: { width: "26%" },
  payColStatus: { width: "16%" },
  payColAmt: { width: "20%", textAlign: "right" },

  /* ── Signature + footer ───────────────────────────────────────── */
  receivedRow: {
    flexDirection: "row",
    marginTop: 14,
    alignItems: "baseline",
  },
  receivedBox: {
    width: 12,
    height: 12,
    border: `1px solid ${BORDER}`,
    marginRight: 6,
  },
  receivedLabel: { fontSize: 9, fontFamily: "Helvetica-Bold" },

  sigRow: { flexDirection: "row", marginTop: 16 },
  sigField: { flex: 1, marginRight: 16 },
  sigLine: { borderBottom: `1px solid ${BORDER}`, height: 18 },
  sigLabel: {
    fontSize: 7,
    color: LABEL,
    textTransform: "uppercase",
    fontFamily: "Helvetica-Bold",
    marginTop: 2,
  },

  copyFooter: {
    position: "absolute",
    bottom: 14,
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 4,
    textTransform: "uppercase",
    color: "#1a1a1a",
  },
  pageNo: {
    position: "absolute",
    bottom: 14,
    right: 28,
    fontSize: 7,
    color: LABEL,
  },
});

function fmtMoney(n: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(n);
}

function fmtDate(iso: string | null | undefined): string {
  if (!iso) return "";
  return new Date(iso).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function fmtDateTime(iso: string | null | undefined): string {
  if (!iso) return "";
  return new Date(iso).toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function methodLabel(m: string): string {
  switch (m) {
    case "credit_card":
      return "Credit Card";
    case "cash":
      return "Cash";
    case "check":
      return "Check";
    case "store_credit":
      return "Store Credit";
    case "gift_card":
      return "Gift Card";
    case "other":
      return "Other";
    default:
      return m.replace(/_/g, " ");
  }
}

export interface PdfCustomerOrderItem {
  department: string | null;
  description: string | null;
  variantNameSnapshot: string | null;
  fabricNameSnapshot: string | null;
  productSkuSnapshot: string | null;
  variantSkuSnapshot: string | null;
  quantity: number;
  unitPrice: number;
  amount: number;
  vendorName: string | null;
}

export interface PdfCustomerOrderPayment {
  receivedAt: string | null;
  paymentMethod: string;
  status: string;
  amount: number;
  cardLast4: string | null;
  cardType: string | null;
  transactionId: string | null;
}

export interface PdfCustomerOrderArgs {
  orderNumber: string;
  placedAt: string;
  salespersonName: string | null;
  customerName: string | null;
  customerPhone: string | null;
  customerAddress: {
    street1: string | null;
    street2: string | null;
    city: string | null;
    state: string | null;
    zip: string | null;
  } | null;
  items: PdfCustomerOrderItem[];
  subtotal: number;
  taxAmount: number;
  deliveryAmount: number;
  total: number;
  depositAmount: number;
  balanceDue: number;
  specialInstructions: string | null;
  payments: PdfCustomerOrderPayment[];
  merchandiseReceived: boolean;
  copy: "customer" | "store" | "delivery";
}

function CustomerInfo({ args }: { args: PdfCustomerOrderArgs }) {
  const a = args.customerAddress;
  const cityLine = a
    ? [a.city, a.state].filter(Boolean).join(", ") +
      (a.zip ? ` ${a.zip}` : "")
    : "";
  return (
    <View style={s.infoTable}>
      <View style={s.infoRow}>
        <View style={[s.infoCell, { width: "60%" }]}>
          <Text style={s.infoLabel}>Date</Text>
          <Text style={s.infoValue}>{fmtDate(args.placedAt)}</Text>
        </View>
        <View style={[s.infoCellLast, { width: "40%" }]}>
          <Text style={s.infoLabel}>Salesperson</Text>
          <Text style={s.infoValue}>{args.salespersonName ?? "—"}</Text>
        </View>
      </View>
      <View style={s.infoRow}>
        <View style={[s.infoCellLast, { width: "100%" }]}>
          <Text style={s.infoLabel}>Name</Text>
          <Text style={s.infoValue}>{args.customerName ?? "—"}</Text>
        </View>
      </View>
      <View style={s.infoRow}>
        <View style={[s.infoCellLast, { width: "100%" }]}>
          <Text style={s.infoLabel}>Address</Text>
          <Text style={s.infoValue}>
            {a?.street1
              ? `${a.street1}${a.street2 ? ", " + a.street2 : ""}`
              : "—"}
          </Text>
        </View>
      </View>
      <View style={s.infoRow}>
        <View style={[s.infoCellLast, { width: "100%" }]}>
          <Text style={s.infoLabel}>City, State, Zip</Text>
          <Text style={s.infoValue}>{cityLine || "—"}</Text>
        </View>
      </View>
      <View style={s.infoRowLast}>
        <View style={[s.infoCellLast, { width: "100%" }]}>
          <Text style={s.infoLabel}>Phone</Text>
          <Text style={s.infoValue}>{args.customerPhone ?? "—"}</Text>
        </View>
      </View>
    </View>
  );
}

function ItemsTable({
  items,
  showVendor,
}: {
  items: PdfCustomerOrderItem[];
  showVendor: boolean;
}) {
  return (
    <View style={s.itemsTable}>
      <View style={s.thRow} fixed>
        <Text style={[s.th, s.colDept]}>Dept</Text>
        <Text style={[s.th, s.colQty]}>Qty</Text>
        <Text style={[s.th, s.colDesc]}>Description</Text>
        <Text style={[s.th, s.colPrice]}>Price</Text>
        <Text style={[s.th, s.colAmt]}>Amount</Text>
      </View>
      {items.map((it, idx) => {
        const sku = it.variantSkuSnapshot ?? it.productSkuSnapshot ?? null;
        const desc =
          it.description || it.variantNameSnapshot || "(no description)";
        const subBits: string[] = [];
        if (sku) subBits.push(`SKU ${sku}`);
        if (it.fabricNameSnapshot) subBits.push(`Fabric: ${it.fabricNameSnapshot}`);
        if (showVendor && it.vendorName) subBits.push(`Vendor: ${it.vendorName}`);
        return (
          <View
            style={s.tdRow}
            key={idx}
            wrap={false}
          >
            <Text style={[s.td, s.colDept]}>{it.department ?? ""}</Text>
            <Text style={[s.td, s.colQty]}>{it.quantity}</Text>
            <View style={[s.colDesc, { paddingHorizontal: 4 }]}>
              <Text style={{ fontSize: 8.5 }}>{desc}</Text>
              {subBits.length > 0 && (
                <Text style={s.itemSub}>{subBits.join(" • ")}</Text>
              )}
            </View>
            <Text style={[s.td, s.colPrice]}>{fmtMoney(it.unitPrice)}</Text>
            <Text style={[s.td, s.colAmt]}>{fmtMoney(it.amount)}</Text>
          </View>
        );
      })}
    </View>
  );
}

function TotalsBox({ args }: { args: PdfCustomerOrderArgs }) {
  const rows: Array<{ label: string; value: number; emphasis?: boolean }> = [
    { label: "Subtotal", value: args.subtotal },
    { label: "Tax", value: args.taxAmount },
    { label: "Delivery", value: args.deliveryAmount },
    { label: "Total", value: args.total, emphasis: true },
    { label: "Deposit", value: args.depositAmount },
    { label: "Bal. Due", value: args.balanceDue, emphasis: true },
  ];
  return (
    <View style={s.totalsBox}>
      {rows.map((r, idx) => (
        <View
          key={r.label}
          style={idx === rows.length - 1 ? s.totalRowLast : s.totalRow}
        >
          <Text style={s.totalLabelCell}>{r.label}</Text>
          <Text
            style={[s.totalValueCell, r.emphasis ? s.totalEmphasis : {}]}
          >
            {fmtMoney(r.value)}
          </Text>
        </View>
      ))}
    </View>
  );
}

function PaymentsBlock({ payments }: { payments: PdfCustomerOrderPayment[] }) {
  if (payments.length === 0) return null;
  const total = payments
    .filter((p) => p.status === "completed" || p.status === "refunded")
    .reduce(
      (sum, p) => sum + (p.status === "refunded" ? -p.amount : p.amount),
      0,
    );
  return (
    // No `wrap={false}` here — the table can grow with many payments and
    // must be allowed to split across pages. The header row is `fixed`
    // (via `<View ... fixed>`) so it repeats on every page break.
    <View style={s.payTable}>
      <Text style={s.payHeader} fixed>Payments on file</Text>
      <View style={s.payThRow} fixed>
        <Text style={[s.payCol, s.payColDate, { color: "#fff", fontFamily: "Helvetica-Bold" }]}>
          Date
        </Text>
        <Text style={[s.payCol, s.payColMethod, { color: "#fff", fontFamily: "Helvetica-Bold" }]}>
          Method
        </Text>
        <Text style={[s.payCol, s.payColRef, { color: "#fff", fontFamily: "Helvetica-Bold" }]}>
          Reference
        </Text>
        <Text style={[s.payCol, s.payColStatus, { color: "#fff", fontFamily: "Helvetica-Bold" }]}>
          Status
        </Text>
        <Text style={[s.payCol, s.payColAmt, { color: "#fff", fontFamily: "Helvetica-Bold" }]}>
          Amount
        </Text>
      </View>
      {payments.map((p, idx) => {
        const ref =
          p.cardLast4 != null
            ? `${p.cardType ?? "Card"} ••${p.cardLast4}`
            : (p.transactionId ?? "");
        return (
          <View style={s.payTdRow} key={idx}>
            <Text style={[s.payCol, s.payColDate]}>
              {fmtDateTime(p.receivedAt)}
            </Text>
            <Text style={[s.payCol, s.payColMethod]}>
              {methodLabel(p.paymentMethod)}
            </Text>
            <Text style={[s.payCol, s.payColRef]}>{ref}</Text>
            <Text style={[s.payCol, s.payColStatus]}>
              {p.status.replace(/_/g, " ")}
            </Text>
            <Text style={[s.payCol, s.payColAmt]}>
              {fmtMoney(p.status === "refunded" ? -p.amount : p.amount)}
            </Text>
          </View>
        );
      })}
      <View
        style={[
          s.payTdRow,
          { borderBottom: 0, backgroundColor: LIGHT_BG },
        ]}
      >
        <Text
          style={[
            s.payCol,
            { width: "80%", fontFamily: "Helvetica-Bold", textAlign: "right" },
          ]}
        >
          Net received
        </Text>
        <Text
          style={[s.payCol, s.payColAmt, { fontFamily: "Helvetica-Bold" }]}
        >
          {fmtMoney(total)}
        </Text>
      </View>
    </View>
  );
}

// Renders one order's full printable page (Customer / Store / Delivery
// copy). Extracted as a standalone sub-component so the Deliveries
// "Merge Delivery Copies" manifest feature (Brief 6, Section 3F Document 2)
// can compose it N times — once per checked order — into a single
// react-pdf <Document>, instead of generating N separate PDF files that
// would then need merging with an external library.
function OrderPdfPage({ args }: { args: PdfCustomerOrderArgs }) {
  const copyLabel =
    args.copy === "customer"
      ? "Customer Copy"
      : args.copy === "store"
        ? "Store Copy"
        : "Delivery Copy";
  return (
      <Page size="LETTER" style={s.page}>
        {/* Header */}
        <View style={s.headerRow}>
          <View style={s.brandCol}>
            <Image src={OASIS_LOGO_DATA_URL} style={s.brandLogo} />
            <Text style={s.brandAddr}>
              {OASIS_ADDR1}
              {"\n"}
              {OASIS_ADDR2}
              {"\n"}
              {OASIS_PHONE}
            </Text>
          </View>
          <View style={s.titleCol}>
            <Text style={s.formTitle}>Special Order</Text>
            <Text style={s.formNumber}>{args.orderNumber}</Text>
          </View>
        </View>

        <CustomerInfo args={args} />
        <ItemsTable items={args.items} showVendor={args.copy !== "customer"} />

        {/* Bottom row may grow when special instructions are long, so let
            react-pdf split it across pages instead of throwing a layout
            error. The notes/totals two-column flex still aligns inside
            whichever page each fragment lands on. */}
        <View style={s.bottomRow}>
          <View style={s.notesBox}>
            <Text style={s.notesLabel}>Special Instructions</Text>
            <Text style={s.notesText}>
              {args.specialInstructions?.trim() || " "}
            </Text>
          </View>
          <TotalsBox args={args} />
        </View>

        <PaymentsBlock payments={args.payments} />

        {args.copy === "delivery" && (
          <>
            <View style={s.receivedRow}>
              <View style={s.receivedBox}>
                {args.merchandiseReceived ? (
                  <Text
                    style={{
                      fontSize: 11,
                      textAlign: "center",
                      fontFamily: "Helvetica-Bold",
                      marginTop: -1,
                    }}
                  >
                    X
                  </Text>
                ) : null}
              </View>
              <Text style={s.receivedLabel}>
                Merchandise Received in Good Condition
              </Text>
            </View>

            <View style={s.sigRow}>
              <View style={s.sigField}>
                <View style={s.sigLine} />
                <Text style={s.sigLabel}>Customer Signature</Text>
              </View>
              <View style={{ width: 140 }}>
                <View style={s.sigLine} />
                <Text style={s.sigLabel}>Date</Text>
              </View>
            </View>
          </>
        )}

        <Text style={s.copyFooter} fixed>
          {copyLabel}
        </Text>
        <Text
          style={s.pageNo}
          fixed
          render={({ pageNumber, totalPages }) =>
            totalPages > 1 ? `Page ${pageNumber} / ${totalPages}` : ""
          }
        />
      </Page>
  );
}

function CustomerOrderDocument(args: PdfCustomerOrderArgs) {
  return (
    <Document>
      <OrderPdfPage args={args} />
    </Document>
  );
}

export async function generateCustomerOrderPdf(
  args: PdfCustomerOrderArgs,
): Promise<Buffer> {
  return renderToBuffer(<CustomerOrderDocument {...args} />);
}

// Deliveries "Generate Delivery Manifest" merge feature (Brief 6, Section
// 3F Document 2): renders one Delivery Copy page per checked order, in the
// order given by the caller, all inside a single react-pdf Document. Each
// order still gets the exact same delivery-copy layout as a standalone
// print (via the shared OrderPdfPage sub-component) — this only changes how
// many pages land in one PDF.
export async function generateMergedDeliveryCopiesPdf(
  argsList: PdfCustomerOrderArgs[],
): Promise<Buffer> {
  return renderToBuffer(
    <Document>
      {argsList.map((args) => (
        <OrderPdfPage key={args.orderNumber} args={args} />
      ))}
    </Document>,
  );
}
