import { Router, type IRouter } from "express";
import healthRouter from "./health";
import geoRouter from "./geo";
import legalRouter from "./legal";
import bannersRouter from "./banners";
import manufacturersRouter from "./manufacturers";
import categoriesRouter from "./categories";
import materialsRouter from "./materials";
import productsRouter from "./products";
import fabricsRouter from "./fabrics";
import adminProductsRouter from "./adminProducts";
import adminProductsImportRouter from "./adminProductsImport";
import adminSetsRouter from "./adminSets";
import adminInventoryRouter from "./adminInventory";
import adminCarriersRouter from "./adminCarriers";
import adminBannersRouter from "./adminBanners";
import adminLegalRouter from "./adminLegal";
import adminSettingsRouter from "./adminSettings";
import adminDiscountsRouter from "./adminDiscounts";
import adminUsersRouter from "./adminUsers";
import adminCustomersRouter from "./adminCustomers";
import notificationsRouter from "./notifications";
import adminAuditRouter from "./adminAudit";
import adminOrdersRouter from "./adminOrders";
import adminVendorOrdersRouter from "./adminVendorOrders";
import adminReportsRouter from "./adminReports";
import authRouter from "./auth";
import staffAuthRouter from "./staffAuth";
import staffRecoveryRouter from "./staffRecovery";
import storageRouter from "./storage";
import wishlistRouter from "./wishlist";
import cartRouter from "./cart";
import accountRouter from "./account";
import checkoutRouter from "./checkout";
import cushionsRouter from "./cushions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(geoRouter);
router.use(legalRouter);
router.use(bannersRouter);
router.use(manufacturersRouter);
router.use(categoriesRouter);
router.use(materialsRouter);
router.use(productsRouter);
router.use(fabricsRouter);
router.use(adminProductsRouter);
router.use(adminProductsImportRouter);
router.use(adminSetsRouter);
router.use(adminInventoryRouter);
router.use(adminCarriersRouter);
router.use(adminBannersRouter);
router.use(adminLegalRouter);
router.use(adminSettingsRouter);
router.use(adminDiscountsRouter);
router.use(adminUsersRouter);
router.use(adminCustomersRouter);
router.use(notificationsRouter);
router.use(adminAuditRouter);
router.use(adminOrdersRouter);
router.use(adminVendorOrdersRouter);
router.use(adminReportsRouter);
router.use(authRouter);
router.use(staffAuthRouter);
router.use(staffRecoveryRouter);
router.use(storageRouter);
router.use(wishlistRouter);
router.use(cartRouter);
router.use(accountRouter);
router.use(checkoutRouter);
router.use(cushionsRouter);

export default router;
