import { Router, type IRouter } from "express";
import healthRouter from "./health";
import legalRouter from "./legal";
import bannersRouter from "./banners";
import manufacturersRouter from "./manufacturers";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import adminProductsRouter from "./adminProducts";
import adminProductsImportRouter from "./adminProductsImport";
import adminSetsRouter from "./adminSets";
import adminInventoryRouter from "./adminInventory";
import adminCarriersRouter from "./adminCarriers";
import adminBannersRouter from "./adminBanners";
import adminLegalRouter from "./adminLegal";
import adminSettingsRouter from "./adminSettings";
import adminDiscountsRouter from "./adminDiscounts";
import adminUsersRouter from "./adminUsers";
import notificationsRouter from "./notifications";
import adminAuditRouter from "./adminAudit";
import adminOrdersRouter from "./adminOrders";
import authRouter from "./auth";
import staffAuthRouter from "./staffAuth";
import storageRouter from "./storage";

const router: IRouter = Router();

router.use(healthRouter);
router.use(legalRouter);
router.use(bannersRouter);
router.use(manufacturersRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(adminProductsRouter);
router.use(adminProductsImportRouter);
router.use(adminSetsRouter);
router.use(adminInventoryRouter);
router.use(adminCarriersRouter);
router.use(adminBannersRouter);
router.use(adminLegalRouter);
router.use(adminSettingsRouter);
router.use(adminDiscountsRouter);
router.use(adminUsersRouter);
router.use(notificationsRouter);
router.use(adminAuditRouter);
router.use(adminOrdersRouter);
router.use(authRouter);
router.use(staffAuthRouter);
router.use(storageRouter);

export default router;
